name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip
      - run: pip install playwright==1.46.0 pillow numpy colorama
      - run: python -m playwright install --with-deps chromium
      - run: nohup python scripts_py/preview.py &
      - run: sleep 2
      - run: python scripts_py/run_ci.py
      - run: python scripts_py/compare_images.py
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            .agent/artifacts/**
            .agent/baseline/**
            .agent/diff/**
            ci_report.md
      - uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ci_report.md
